---
dependencies: []

# This role will deploy the Database on the provisioned enviornment
galaxy_info:
  author: opensource
  description: PostgreSQL server for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - database
    - postgresql
    - postgres
    - rdbms
